blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/TrackMan/.github/discussions
    about: Please ask questions or start discussions in our discussions forum
